name="hono-minimal"
main="src/index.ts"

compatibility_date = "2022-11-22"

[[ d1_databases ]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "db1"
database_id = "398b1748-62d5-47dd-9f86-799c429e7d63"
preview_database_id = "0236088e-97a0-4cf2-9d80-64f96e0d2abb"